### PR TITLE
update : remove loader #3 Removed loader from 3 files i.e. index.html, style.css and main.js

### PR DESCRIPTION
**Pull request by bhumikadubey**
## Checklist
- [x] I have read and agree to abide by the [Code of Conduct](https://github.com/tcet-opensource/.github/blob/main/CODE_OF_CONDUCT.md)
- [x] I have read and followed the **Contributing Guidelines**

### CODE REVIEW

**Comment by demonkillerr** [comment]
@AtharvaTanpure18 due you want to merge this in?

**Comment by AtharvaTanpure18** [comment]
We were testing our workflow.
You will be the last person to review right ?

**Comment by bhumikadubey** [comment]
> We were testing our workflow. You will be the last person to review right ?

Yes

**Comment by bhumikadubey** [comment]
> @AtharvaTanpure18 due you want to merge this in?

If the merge is bug free then yes

**Comment by AtharvaTanpure18** [comment]
Solved

**Pull request closed without merging**
